export const MAX_REQUEST_BODY_BYTES = 16_384;
export const MAX_DISPLAY_NAME_LENGTH = 200;
export const MAX_CANONICAL_URL_LENGTH = 2048;
export const MAX_ERROR_MESSAGE_LENGTH = 500;

export const DEFAULT_LIST_LIMIT = 20;
export const MAX_LIST_LIMIT = 100;

export const IDEMPOTENCY_RETENTION_HOURS = 24;

export const FROZEN_ERROR_CODES = [
  "INVALID_REQUEST",
  "INVALID_CANONICAL_URL",
  "CANONICAL_URL_ALREADY_REGISTERED",
  "RATE_LIMITED",
  "UNAUTHORIZED",
  "SITE_NOT_FOUND",
  "SITE_DELISTED",
  "IDEMPOTENCY_CONFLICT",
  "INTERNAL_ERROR",
] as const;

export type FrozenErrorCode = (typeof FROZEN_ERROR_CODES)[number];
